WorkspaceDirectories = []
FormatOnPut = true
CodeActionsOnPut = ["source.organizeImports"]

[Servers]
	[Servers.gopls]
	Command = ["gopls", "serve"]
	StderrFile = "gopls.stderr.log"
	LogFile = "gopls.log"

		# These settings gets passed to gopls
		[Servers.gopls.Options]
		hoverKind = "FullDocumentation"

	[Servers.typescript-ls]
	Command = ["typescript-language-server", "--stdio"]

[[FilenameHandlers]]
  Pattern = "[/\\\\]go\\.mod$"
  LanguageID = "go.mod"
  ServerKey = "gopls"

[[FilenameHandlers]]
  Pattern = "[/\\\\]go\\.sum$"
  LanguageID = "go.sum"
  ServerKey = "gopls"

[[FilenameHandlers]]
  Pattern = "\\.go$"
  LanguageID = "go"
  ServerKey = "gopls"

[[FilenameHandlers]]
  Pattern = "\\.ts$"
  LanguageID = "typescript"
  ServerKey = "typescript-ls"

[[FilenameHandlers]]
  Pattern = "\\.mts$"
  LanguageID = "typescript"
  ServerKey = "typescript-ls"

[[FilenameHandlers]]
  Pattern = "\\.tsx$"
  LanguageID = "typescriptreact"
  ServerKey = "typescript-ls"
