# bash_profileのデフォルト設定を書くファイル
#
# インストールする場所が変わるものは環境ごとに調整する
# 1. Goコンパイラ(GOROOT)
#
# 入れるかどうか分からないものも環境ごとに書く
# 1. Nixpkgs
# 2. Cocoapods

# XDG Base Directory
#export XDG_CONFIG_HOME=~/.config

export PATH=$PATH:~/bin

# Plan 9
export PLAN9=/usr/local/plan9
export PATH=$PATH:$PLAN9/bin

#/mnt/font/HiraKakuPro-W3/14a/font
export font=/mnt/font/GoMono/14a/font
export secstore=localhost	# /lib/ndbに書くべきか...
export BROWSER=firefox		# safari, firefox or google-chrome

# golang
export PATH=$PATH:~/go/bin
export GOPATH=~
export PATH=$GOPATH/bin:$PATH	# ~/binなので先頭に必要
export GOROOT_BOOTSTRAP=~/go1.9

export CSEARCHINDEX=~/lib/csearchindex

# GCP
export PATH=$PATH:~/pkg/google-cloud-sdk/bin

# NodeJS
export NPM_CONFIG_USERCONFIG=~/lib/npmrc

export LESSHISTFILE=-

if [[ $TERM = dumb ]]
then
	export NO_COLOR=1
fi
