# bash_profileのデフォルト設定を書くファイル
#
# インストールする場所が変わるものは環境ごとに調整する
# 1. Goコンパイラ(GOROOT)
#
# 入れるかどうか分からないものも環境ごとに書く
# 1. Nixpkgs
# 2. Cocoapods

# Plan 9
#/mnt/font/HiraKakuPro-W3/14a/font
export font=/mnt/font/GoMono/14a/font
export secstore=localhost	# /lib/ndbに書くべきか...
export BROWSER=safari		# safari or google-chrome

# golang
export PATH=$PATH:~/go/bin
export GOPATH=~
export PATH=$GOPATH/bin:$PATH	# ~/binなので先頭に必要
export GOROOT_BOOTSTRAP=~/go1.9

# GCP
export PATH=$PATH:~/pkg/google-cloud-sdk/bin

# Nixpkgs
#export NIX_PATH=nixpkgs=~/nixpkgs:$NIX_PATH

# NodeJS
export NVM_DIR=~/pkg/nvm
if [[ -f $NVM_DIR/nvm.sh ]]
then
	. $NVM_DIR/nvm.sh
fi

# Ruby
#export GEM_HOME=~/pkg/gem/ruby/$(ruby -e 'puts RUBY_VERSION')
#export PATH=$PATH:$GEM_HOME/bin

# Cocoapods
#export CP_HOME_DIR=~/pkg/cocoapods

export LESSHISTFILE=-
